---
title: "9555projectPart1"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: '3'
    toc_float: yes
  prettydoc::html_pretty:
    theme: hpstr
    highlight: vignette
    toc: yes
    toc_depth: '3'
  html_notebook:
    toc: yes
    toc_depth: '3'
    toc_float: yes
---
#Read in data
```{r echo = FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(lavaan)
library(semPlot)
library(data.table)
library(rmarkdown)
library(knitr)

setwd('/Users/tzhu9/Google Drive/ExecFcnBattery/Analysis')
data<-read.csv('overall.badremoved.chanceremoved.DATA.csv')
data<-select(data, 
             "Subj", 
             "Antisaccade", 
             #"Stroop", 
             "StroopPerf", 
             "SSRTavg", 
             "LetMem", 
             "KeepTrack", 
             "SpatialBack", 
             "NumLett", 
             #"NumLetPerf", 
             "ColShape", 
             #"ColShapePerf", 
             "CatSwitch", 
             #"CatSwitchPerf", 
             "FR1", "FR2", "FR3", "FR4", 
             "SD1", "SD2", "SD3", "SD4")

data$Subj<-as.factor(data$Subj)

#Standardize all columns except subjects
data[,-c(1)]=scale(data[,-c(1)])
```
 
```{r}
kable(head(data))
```

#CFA Model testing construct
```{r}
setwd('/Users/tzhu9/Google Drive/ExecFcnBattery/Analysis')

cfaModel<-'
Inhibit=~StroopPerf+SSRTavg+Antisaccade
Update=~KeepTrack+SpatialBack+LetMem
Shift=~NumLett+ColShape+CatSwitch
SD=~SD1+SD2+SD3+SD4
FR=~FR1+FR2+FR3+FR4
'
cfaFit <- cfa(cfaModel, data, std.lv=T, missing = 'ml')
summary(cfaFit, fit.measures=T,standardized=T, rsquare=T)
```

#Second-order CFA Model and having SD category regress on EF
```{r}
higher_cfaModel<-'
Inhibit=~StroopPerf+SSRTavg+Antisaccade
Update=~KeepTrack+SpatialBack+LetMem
Shift=~NumLett+ColShape+CatSwitch
EF=~Inhibit+Update+Shift

SD=~SD1+SD2+SD3+SD4

SD~EF
'
higher_cfaFit <- cfa(higher_cfaModel, na.omit(data), std.lv=T)
summary(higher_cfaFit, fit.measures=T,standardized=T, rsquare=T)
```

###Mean and Cov Matrix for Latent Growth Model, calculation omitted
```{r}
cov<-lav_matrix_lower2full(c(0.9654194,
                  0.5852688, 0.7881355,
                  0.4177646, 0.5908290, 0.7622064,
                  0.3155825, 0.4811724, 0.5800750, 0.6736341))
mean<-c(0.6663589, 0.7679913, 0.7845376, 0.7895954)
```

#Latent Growth Model where EF predicts i and s in SD category
```{r}
#reload data so that the category blocks are not standardized
setwd('/Users/tzhu9/Google Drive/ExecFcnBattery/Analysis')
df<-read.csv('overall.badremoved.chanceremoved.DATA.csv')
df<-select(df, 
             "Subj", 
             "Antisaccade", 
             #"Stroop", 
             "StroopPerf", 
             "SSRTavg", 
             "LetMem", 
             "KeepTrack", 
             "SpatialBack", 
             "NumLett", 
             #"NumLetPerf", 
             "ColShape", 
             #"ColShapePerf", 
             "CatSwitch", 
             #"CatSwitchPerf", 
             "FR1", "FR2", "FR3", "FR4", 
             "SD1", "SD2", "SD3", "SD4")

df$Subj<-as.factor(df$Subj)

#Standardize the RT data cols
df[,c(2:10)]=scale(df[,c(2:10)])

latModel<-'
#assuming EF is extracted from all tasks
EF=~StroopPerf+SSRTavg+Antisaccade+KeepTrack+SpatialBack+LetMem+NumLett+ColShape+CatSwitch

#intercept and slope
i=~1*SD1+1*SD2+1*SD3+1*SD4
s=~0*SD1+1*SD2+2*SD3+3*SD4

#regression
i~EF
s~EF
'

latfit <- growth(latModel,std.lv=T,
                 df)
summary(latfit,fit.measures=T)
```















